In [1]:
import numpy as np

In [2]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
], )
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.ndim

2

In [11]:
a.size

6

In [13]:
a.shape

(2, 3)

In [14]:
a.dtype

dtype('int32')

In [25]:
b = np.array([
    [
        [12, 13, 14],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
b

array([[[12, 13, 14],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [26]:
b.ndim

3

In [27]:
# b[1, 0, 1] = 99
b[1, 0, 1]

5

In [28]:
b[:, :1]

array([[[12, 13, 14]],

       [[ 6,  5,  4]]])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a[1] = 10
a

array([[ 1,  2,  3],
       [10, 10, 10]])

In [33]:
a[1] = np.array([20, 30, 40])
a

array([[ 1,  2,  3],
       [20, 30, 40]])

In [43]:
a.mean()

31.0

In [58]:
a.mean(axis=0)

array([25.5, 31. , 36.5])

In [59]:
a.mean(axis=1)

array([ 2., 60.])

In [44]:
a.std()

29.574764017091777

In [71]:
c = np.arange(8)
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [72]:
c += 8
c

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [74]:
[i * 8 for i in c]

[64, 72, 80, 88, 96, 104, 112, 120]

In [77]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [78]:
b = np.array([10, 20, 30, 40])
b

array([10, 20, 30, 40])

In [79]:
a + b

array([10, 21, 32, 43])

In [84]:
b - a

array([10, 19, 28, 37])

In [88]:
a[[-2, 0]]

array([2, 0])

In [90]:
a[[True, True, False, True]]

array([0, 1, 3])

In [92]:
a >= 2

array([False, False,  True,  True])

In [3]:
a[a >= 2]

array([2, 3, 4, 5, 6])

In [4]:
a.mean()

3.5

In [8]:
a[1] = 0
a

array([[1, 2, 3],
       [0, 0, 0]])

In [12]:
a[(a <= 0) | (a >= 2)]

array([2, 3, 0, 0, 0])

In [17]:
a[(a > 0) & (a <= 2)]

array([1, 2])

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
B = np.array([
    [0, 9, 8],
    [7, 6, 5],
    [4, 3, 2]
])
B

array([[0, 9, 8],
       [7, 6, 5],
       [4, 3, 2]])

In [32]:
A.dot(B)

array([[ 26,  30,  24],
       [ 59,  84,  69],
       [ 92, 138, 114]])

In [33]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
l = list(range(10000))
n = np.arange(10000)

In [61]:
%time sum(l)

Wall time: 0 ns


49995000

In [62]:
%time np.sum(n)

Wall time: 0 ns


49995000

In [63]:
%time sum(n)

Wall time: 6.55 ms


49995000

In [64]:
np.random.random(size=5)

array([0.08779038, 0.5028316 , 0.11119868, 0.49430319, 0.83788635])

In [71]:
np.random.normal(5)

5.407344777291723

In [72]:
np.random.randn(5)

array([-0.07543619,  0.06242202,  0.62802167, -0.36755416, -0.17392561])

In [73]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [75]:
np.arange(5, 2)

array([], dtype=int32)

In [78]:
np.arange(5, 3, 2)

array([], dtype=int32)

In [81]:
np.arange(6).reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [88]:
np.linspace(0, 1, 10, False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [90]:
np.zeros(10).reshape((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [96]:
np.linspace(10, 49, 10).reshape((5, 2))

array([[10.        , 14.33333333],
       [18.66666667, 23.        ],
       [27.33333333, 31.66666667],
       [36.        , 40.33333333],
       [44.66666667, 49.        ]])

In [102]:
np.empty(9).reshape((3, 3))

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [111]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])