In [6]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats

np.set_printoptions(precision=3)

In [2]:
x = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y = np.array([[0, 3, 2], [7, 4, 5], [1, 8, 9]])
y

array([[0, 3, 2],
       [7, 4, 5],
       [1, 8, 9]])

In [4]:
x*y

array([[ 0,  6,  6],
       [28, 20, 30],
       [ 7, 64, 81]])

In [5]:
np.dot(x, y)

array([[ 17,  32,  37],
       [ 41,  80,  87],
       [ 65, 125, 135]])

In [27]:
cars = pd.read_csv('mtcars.csv')
cars.rename(columns={'Unnamed: 0': 'car_names'}, inplace=True)

In [28]:
cars.head()

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [29]:
cars.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

In [30]:
cars.sum(axis=1)

0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

In [31]:
cars.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [77]:
np.printoptions(precision=3)
cars.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [36]:
cars['mpg'].mean()

20.090624999999996

In [39]:
only_disp = cars.disp
only_disp.idxmax()

14

In [40]:
cars.max()

car_names    Volvo 142E
mpg                33.9
cyl                   8
disp                472
hp                  335
drat               4.93
wt                5.424
qsec               22.9
vs                    1
am                    1
gear                  5
carb                  8
dtype: object

In [41]:
cars.min()

car_names    AMC Javelin
mpg                 10.4
cyl                    4
disp                71.1
hp                    52
drat                2.76
wt                 1.513
qsec                14.5
vs                     0
am                     0
gear                   3
carb                   1
dtype: object

In [42]:
cars.std()

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [45]:
am = cars.am
am.value_counts()

0    19
1    13
Name: am, dtype: int64

In [46]:
cars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [47]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   car_names  32 non-null     object 
 1   mpg        32 non-null     float64
 2   cyl        32 non-null     int64  
 3   disp       32 non-null     float64
 4   hp         32 non-null     int64  
 5   drat       32 non-null     float64
 6   wt         32 non-null     float64
 7   qsec       32 non-null     float64
 8   vs         32 non-null     int64  
 9   am         32 non-null     int64  
 10  gear       32 non-null     int64  
 11  carb       32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [51]:
carb = cars.carb
carb

0     4
1     4
2     1
3     1
4     2
5     1
6     4
7     2
8     2
9     4
10    4
11    3
12    3
13    3
14    4
15    4
16    4
17    1
18    2
19    1
20    1
21    2
22    2
23    4
24    2
25    1
26    2
27    2
28    4
29    6
30    8
31    2
Name: carb, dtype: int64

In [52]:
carb.value_counts()

4    10
2    10
1     7
3     3
8     1
6     1
Name: carb, dtype: int64

In [58]:
# cars.index = cars.car_name
# cars_cat
cars.columns

Index(['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [63]:
cars.index = cars.car_names
cars_cat = cars[['am', 'cyl', 'vs', 'gear', 'carb']]

cars_cat.head(15)

am  cyl  vs  gear  carb
car_names                                  
Mazda RX4            1    6   0     4     4
Mazda RX4 Wag        1    6   0     4     4
Datsun 710           1    4   1     4     1
Hornet 4 Drive       0    6   1     3     1
Hornet Sportabout    0    8   0     3     2
Valiant              0    6   1     3     1
Duster 360           0    8   0     3     4
Merc 240D            0    4   1     4     2
Merc 230             0    4   1     4     2
Merc 280             0    6   1     4     4
Merc 280C            0    6   1     4     4
Merc 450SE           0    8   0     3     3
Merc 450SL           0    8   0     3     3
Merc 450SLC          0    8   0     3     3
Cadillac Fleetwood   0    8   0     3     4

In [65]:
gears_group = cars_cat.groupby('gear')
gears_group.describe()

am                                                cyl            ...  \
     count      mean       std  min  25%  50%  75%  max count      mean  ...   
gear                                                                     ...   
3     15.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  15.0  7.466667  ...   
4     12.0  0.666667  0.492366  0.0  0.0  1.0  1.0  1.0  12.0  4.666667  ...   
5      5.0  1.000000  0.000000  1.0  1.0  1.0  1.0  1.0   5.0  6.000000  ...   

       vs       carb                                               
      75%  max count      mean       std  min  25%  50%  75%  max  
gear                                                               
3     0.0  1.0  15.0  2.666667  1.175139  1.0  2.0  3.0  4.0  4.0  
4     1.0  1.0  12.0  2.333333  1.302678  1.0  1.0  2.0  4.0  4.0  
5     0.0  1.0   5.0  4.400000  2.607681  2.0  2.0  4.0  6.0  8.0  

[3 rows x 32 columns]

In [72]:
cars['group'] = pd.Series(cars.gear, dtype='category')
cars['group'].dtypes

CategoricalDtype(categories=[3, 4, 5], ordered=False)

In [74]:
cars['group'].value_counts()

3    15
4    12
5     5
Name: group, dtype: int64

In [75]:
pd.crosstab(cars['am'], cars['gear'])

gear   3  4  5
am            
0     15  4  0
1      0  8  5